//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary_Line
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diary_Line()
        {
            this.Diary_Product = new HashSet<Diary_Product>();
        }
    
        public int ID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<float> Glucose { get; set; }
        public Nullable<int> ID_GeneralDiary_Person { get; set; }
        public Nullable<bool> IsDoseLower { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diary_Product> Diary_Product { get; set; }
        public virtual GeneralDiary_Person GeneralDiary_Person { get; set; }
    }
}
