//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diary_Product
    {
        public int ID { get; set; }
        public Nullable<int> ID_Diary_Line { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<float> Grams { get; set; }
        public float He
        {
            get { return (float)(Grams * Product.Carbohydrates / 100 / 10.00); }
        }
       
        public virtual Diary_Line Diary_Line { get; set; }
        public virtual Product Product { get; set; }
    }
}
