//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiabetApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u1683604_DiabetDBEntities : DbContext
    {
        public u1683604_DiabetDBEntities()
            : base("name=u1683604_DiabetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    

        public virtual DbSet<Diary_Line> Diary_Line { get; set; }
        public virtual DbSet<Diary_Product> Diary_Product { get; set; }
        public virtual DbSet<GeneralDiary_Person> GeneralDiary_Person { get; set; }
        public virtual DbSet<Glycemic_Index> Glycemic_Index { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }

        public virtual DbSet<Type_Product> Type_Product { get; set; }
    }
}
